### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by guillaume-fr** [quozd/awesome-dotnet#107]
I don't know how/if we can do it but that would be great to have some information about licensing of linked projects. Basically : is the linked library free in a commercial product ?

**Comment by quozd** [comment]
All commercial products in the list have **[$]** tag in the description. The rest is open source by default.

**Comment by guillaume-fr** [comment]
ITextSharp is open source and free for open source projects but also a commercial product requiring payment if your project is not open source. How should we tag such project ?

**Comment by quozd** [comment]
ITestSharp should have **[$]** tag as it requires license and also it should have **[Free for OSS]** tag. Both cases are described in our [Contribution guidelines](https://github.com/quozd/awesome-dotnet/blob/master/CONTRIBUTING.md#proprietarycommercial-software-notice)

So, we need to fix ITextSharp link on the list :) Thanks
