### ISSUE TITLE
CI is no longer working due to a Travis change from .org to .com

### ISSUE THREAD

**Issue by GevorDanielyan** [quozd/awesome-dotnet#1086]
I added pull request few hours ago, but failed action publish to nuget, how can I fix it?

**Comment by pleb** [comment]
Seems like Travis made it so the org isn't available to build from. Not your fault @GevorDanielyan

**Comment by pleb** [comment]
Might be time to investigate using GH Actions

**Comment by GevorDanielyan** [comment]
Ok @pleb , thank you.
