### ISSUE TITLE
The book section

### ISSUE THREAD

**Issue by Jogai** [quozd/awesome-dotnet#1106]
Almost all the books are from just 2 publishers, and 'suggested' by the same contributors. It smells like some kind of promotion. What do others think, and what would be the best to do?

**Comment by pleb** [comment]
Personally, I don't have a problem with it. A fair few of the contributions are from people promoting their work. So I figure, sure, the awesome list is part promotion. 

That said, it's hard to gauge if a book is awesome or not without reading it or having the community vouch for it

**Comment by Jogai** [comment]
The self promotion is true, but at least you can check a few basics in a project, like has it clear documentation, unit tests, examples etc. For a book its harder like you said, and you need to pay right away, which could be a incentive to promote material that's not necessary awesome. Maybe adding a paid resource needs stricter rules about how to prove the awesomeness.

**Comment by pepijnsitter** [comment]
What about free Microsoft ebooks like this one:

https://learn.microsoft.com/en-us/dotnet/architecture/microservices/?WT.mc_id=dotnet-35129-website

I would like to add them somewhere because I have actually enjoyed reading (parts) of it. 

ps I don't work for Microsoft.

**Comment by Jogai** [comment]
There's no subdivision for free books, just add them wherever I'd say

**Comment by Fb9027** [comment]
##- [ ] -

**Comment by pleb** [comment]
I've removed the book section, as generally a web search is a better method to find books, and the book section isn't well maintained
