### ISSUE TITLE
missing a license

### ISSUE THREAD

**Issue by arthurvr** [quozd/awesome-dotnet#117]
This repo misses a license. Let's add one :)

You can use https://github.com/sindresorhus/awesome#license as inspiration.

**Comment by quozd** [comment]
^_^ completely forgot about license. thanks a lot. would you like to create your own PR? :)

**Comment by arthurvr** [comment]
Well, which license would you like? Public domain alright for you?

**Comment by quozd** [comment]
Yep :) Public domain is pretty good.
