### ISSUE TITLE
replace pinvoke  with  https://github.com/microsoft/CsWin32

### ISSUE THREAD

**Issue by heartacker** [quozd/awesome-dotnet#1182]
[P/Invoke](https://github.com/dotnet/pinvoke#pinvoke)
⚠ NOTICE: https://github.com/dotnet/pinvoke/issues/565: A new, preferred approach for Win32 p/invokes now exists for C# developers.

This repo is no longer maintained.

**Comment by pleb** [comment]
@heartacker PR?
