### ISSUE TITLE
so many dead libraries

### ISSUE THREAD

**Issue by gsmental** [quozd/awesome-dotnet#1190]
there are so many dead/obsolete libraries are listed in the list. please remove which are read-only, obsolete, not maintained since years, declared unsupported.

**Comment by pleb** [comment]
> there are so many dead/obsolete libraries are listed in the list. please remove which are read-only, obsolete, not maintained since years, declared unsupported.

Feel free to open PRs removing dead/obsolete libraries, @gsmental
