### ISSUE TITLE
Add CodeBehind Framework in Web Frameworks Section

### ISSUE THREAD

**Issue by elanatframework** [quozd/awesome-dotnet#1219]
[CodeBehind Framework](https://github.com/elanatframework/Code_behind) - CodeBehind Framework is a modern backend framework under .NET Core that competes with Microsoft's default web frameworks (ASP.NET Core MVC and Razor Pages).

![ASP.NET Core web frameworks list](https://github.com/quozd/awesome-dotnet/assets/111444759/931894e9-64f0-4380-b446-cee409935cd7)

**Comment by pleb** [comment]
@elanatframework feel free to raise a PR
