### ISSUE TITLE
Looking for collaborators.

### ISSUE THREAD

**Issue by quozd** [quozd/awesome-dotnet#134]
Hey folks. I think our awesome-dotnet list is very important for the community, but I don't have enough time to check all PRs in a proper way to ensure they follow our quality standards. 

So, If you like .NET, feel experienced enough and have some time to help me with PRs, feel free to leave a comment here or drop me a few lines to email (can be found in my profile) and will make you a collaborator.

Thanks guys.

**Comment by devkhan** [comment]
I am willing to be a collaborator in this repository. I see there are many tools, frameworks, etc that are missing in the list. I understand that you and other collaborators have time constraints.

So, if you want to, I can add to the list and checking PRs.

Thank You. :smiley:

**Comment by kiquenet** [comment]
Only tools and frameworks awesome please

**Comment by devkhan** [comment]
Sure @kiquenet. I will only add projects which are awesome. Only awesome. :+1:

**Comment by quozd** [comment]
@devkhan added you as collaborator. :+1: Let's see how it will be going. Don't forget to read carefully our quality standards and contribution guidelines. @vladen and I will still participate in this party ;)

Thanks

**Comment by devkhan** [comment]
Looking forward to it. Thank you very much. :smiley:

**Comment by quozd** [comment]
Reopened. Collaborators are welcome :)

**Comment by Jeffiy** [comment]
I am willing to be a collaborator in this repository too, Thanks.

**Comment by quozd** [comment]
@Jeffiy, permissions granted :) Welcome

**Comment by pleb** [comment]
Happy to collaborate. I promise to uphold the standards.

**Comment by quozd** [comment]
@pleb welcome. 

cc @vladen @Jeffiy @devkhan

**Comment by Jeffiy** [comment]
@pleb welcome.

**Comment by pleb** [comment]
Hey everyone. Looking forward to helping out. @quozd @vladen @Jeffiy @devkhan

**Comment by vladen** [comment]
Hey @pleb! Glad to see you among us.
