### ISSUE TITLE
Make animated online videos

### ISSUE THREAD

**Issue by Jorgelig** [quozd/awesome-dotnet#153]
some libraries to create videos like http://www.wideo.co/ ?

**Comment by quozd** [comment]
How is it related to our list?

**Comment by Jorgelig** [comment]
Is recourse to handle multimedia, this provided the "Media" section (https://github.com/quozd/awesome-dotnet#media)

**Comment by quozd** [comment]
I can't see any .NET related stuff there. Just some commercial service. Sorry, but I can't merge it.
