### ISSUE TITLE
Add a link to awesome-linq

### ISSUE THREAD

**Issue by aloisdg** [quozd/awesome-dotnet#178]
Hello,

I just created an [awesome list for LINQ](https://github.com/aloisdg/awesome-linq). I started as a PR to awesome-dotnet but I move to a new list when I realized the size of it. Well, I think it would be a good idea to link awesome-linq list to awesome-dotnet. Your thoughts?

Also, as awesome-linq is quite new, I would love some feedbacks from you.
Thank you.

Cheers,

**Comment by devkhan** [comment]
Link please?

**Comment by aloisdg** [comment]
@devkhan Well I forgot it. Here it is : [awesome-linq](https://github.com/aloisdg/awesome-linq).

Thank you.

**Comment by devkhan** [comment]
Can you please open a PR adding your list to the "Other Lists" section at the bottom? I'll merge it.

**Comment by aloisdg** [comment]
Done :)

**Comment by devkhan** [comment]
Merged. :+1:
