### ISSUE TITLE
Add "Include url to added project in commit message" rule

### ISSUE THREAD

**Issue by pmbanka** [quozd/awesome-dotnet#229]
I would like to use this repository as a source of knowledge about interesting projects. I'm watching the repository and receive email updates every time something happens here. Unfortunately, the form of received emails do not fit my workflow really well.

As you can see below, there is no clickable URL to the project page in the email itself:

![image](https://cloud.githubusercontent.com/assets/9840334/11495783/2fd0888a-980e-11e5-8bc2-65677b97adcb.png)

So, currently I click on README.md, then I select the URL and copy-paste it to the new card. Would it be possible to encourage people to add relevant URL to the commit summary? Based on the number of people watching this repository, I assume I'm not the only one using it similarly.

**Comment by quozd** [comment]
Hi @pmbanka, Unfortunately, I think it is not possible. We already have some rules how to write PR descriptions, but people just ignore them :( There is nothing i can do.

**Comment by joelcollinsdc** [comment]
Strongly agree with @pmbanka.  Ask them to modify the PR summary?

**Comment by quozd** [comment]
@joelcollinsdc you will still get initial email without the link. and then one more with my message asking for a better commit summary, and then one more with changes. Do we really want it?

**Comment by quozd** [comment]
I totally agree with you guys, but its hard to force people to follow some rules :(

**Comment by pleb** [comment]
Long and complex way:

Have a bot moderate the PRs. "Thanks for contributing, looks like you're missing the link in the PR comment", or "Thanks for contributing, looks like you have a line ending issue. Please fix and update the PR". But would it be worth the effort?

**Comment by quozd** [comment]
@pleb maybe there are some ready-to-use bot out there?

**Comment by pleb** [comment]
@quozd didn't find anything that fits the intended usage :(

**Comment by quozd** [comment]
Fixed by adding Pull request template
