### ISSUE TITLE
Fix broken URLs found by awesome-bot

### ISSUE THREAD

**Issue by quozd** [quozd/awesome-dotnet#260]
### Broken links 

  1. 302 http://nemerle.org → /About
  2. 301 http://sourceforge.net/projects/firebird/ → https://sourceforge.net/projects/firebird/
  3. 301 http://tmenier.github.io/Flurl → http://tmenier.github.io/Flurl/
  4. 301 https://code.google.com/p/markdownsharp/ → https://code.google.com/archive/p/markdownsharp
  5. 301 https://github.com/nblumhardt/stateless → https://github.com/dotnet-state-machine/stateless
  6. https://lean.quantconnect.com SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
  7. 301 http://i.creativecommons.org/p/zero/1.0/88x31.png → https://licensebuttons.net/p/zero/1.0/88x31.png
  8. 301 http://wamp.ws → http://wamp-proto.org/

### Dupes 

  1. https://github.com/NancyFx/Nancy
  2. https://github.com/dotnet/orleans
  3. https://github.com/spring-projects/spring-net
  4. http://www.myget.org/
  5. https://www.myget.org/opensource
  6. http://tpetricek.github.io/FSharp.Formatting/
  7. http://fsharp.github.io/FSharp.Data/
  8. https://github.com/JoshClose/CsvHelper

**Comment by ReadmeCritic** [comment]
I'm on it

**Comment by quozd** [comment]
:+1: Thanks
