### ISSUE TITLE
Can Open Live Writer be added to this?

### ISSUE THREAD

**Issue by devkhan** [quozd/awesome-dotnet#263]
[Open Live Writer](https://github.com/OpenLiveWriter/OpenLiveWriter/) - Blog writer for desktop Windows. Also, if yes, in which category to add this?

**Comment by quozd** [comment]
Feel free to create Tools category

**Comment by devkhan** [comment]
Added. 6463f0267b860182e43750b6a4ae5c097ed2d06a
