### ISSUE TITLE
Link to awesome-analyzers?

### ISSUE THREAD

**Issue by ig-sinicyn** [quozd/awesome-dotnet#278]
Hi!

The **Other Lists** category definitely missing the 
https://github.com/Cybermaxs/awesome-analyzers :)

**Comment by devkhan** [comment]
If you can open a PR, it'd be great. Otherwise, I'll add in a couple of days. :+1:

**Comment by ig-sinicyn** [comment]
Ok, will do:)

**Comment by ig-sinicyn** [comment]
Done, #279
