### ISSUE TITLE
Add NGon library for ASP.NET MVC - send data from C# to JavaScript easily

### ISSUE THREAD

**Issue by code4aman** [quozd/awesome-dotnet#295]
Initial repo is [here](https://github.com/brooklynDev/NGon) - but this repo seems to be abandoned. I have updated version with MVC 5 support [here](https://github.com/code4aman/NGonAlt).
I couldn't define in which category to add, Misc maybe?

**Comment by pleb** [comment]
My vote is for an MVC or MVC Extension category

Cool library, good to see you're taken in on

**Comment by code4aman** [comment]
If you mean to create new category, then IMO just `ASP.NET` is OK and `MVC` is too narrow.
