### ISSUE TITLE
Remove the duplicate CefSharp

### ISSUE THREAD

**Issue by hgupta9** [quozd/awesome-dotnet#438]
The first CefSharp is a dup and listed under "Interoperability". This has a complicated description and is under the wrong category. Please remove it.

**Comment by pleb** [comment]
@hgupta9 any chance of a PR?

**Comment by pleb** [comment]
Referenced wrong ticket. My bad

**Comment by pleb** [comment]
@hgupta9 Don't worry. I've taken care of this. Thanks for reporting it ;)
