### ISSUE TITLE
Proposal for @zihotki to join the team

### ISSUE THREAD

**Issue by pleb** [quozd/awesome-dotnet#449]
I would like to propose that @zihotki becomes a collaborator.

- His feedback on submitted PRs has been, to date, of a high quality
- He has been a regular in monitoring PR requests
- I think he would be a valuable member of the team.

I believe that if @quozd agrees and @zihotki accepts that this should be a done deal.

Thoughts?

**Comment by quozd** [comment]
Invite sent.
Welcome on board, @zihotki
