### ISSUE TITLE
Move License information to make it easier to access

### ISSUE THREAD

**Issue by zihotki** [quozd/awesome-dotnet#494]
Currently the license is positioned at the bottom and it's hard to find it. So what do you think about moving it to the top and/or creating a license file in the repository itself?

**Comment by patricksadowski** [comment]
I vote for license file and a link to it.

**Comment by VPashkov** [comment]
The advantage of license file is that GitHub understand it and shows in summary bar.

**Comment by pleb** [comment]
👍
