### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by Jogai** [quozd/awesome-dotnet#547]
I just returned from a break, and now I see that submissions are labeled. When did the labels get introduced? I cant find anything about it in the contributing guide. Do we have to vote for awesome projects? Or did we need to do that anyway? (I'm happy to)

I'm watching this project, but only now noticed it...

**Comment by pleb** [comment]
@Jogai I added the labels so the mods could easily provide feedback on a submission which can't be approved and merged straight way. It saves mods from having to write a lengthy reply.

As for the voting, if the mod has doubt as to whether the project is awesome, it allows for the community to rally behind the project and show support - if they wish
