### ISSUE TITLE
A library / framework for inclusion

### ISSUE THREAD

**Issue by tr8dr** [quozd/awesome-dotnet#548]
Hi,  I've authored a .NET library / server that allows bridging between Python -> .NET  or R -> .NET.     .NET objects can be created and interacted with seamlessly in R or Python.   The project is at:

https://github.com/tr8dr/.Net-Bridge

The python extension "pydotnet" is available via the usual pip installer and the R extension is to be released soon on CRAN.

Would be pleased if this is added to your list in an appropriate category.  Thanks

**Comment by pleb** [comment]
@tr8dr the normal route to get something added to the list would be via a PR
