### ISSUE TITLE
Image Processing

### ISSUE THREAD

**Issue by kiquenet** [quozd/awesome-dotnet#56]
I'm newbie with image processing and C#.

I don't know which are  Frameworks awesome about it. 

For example, I have seen those:

AForge
http://www.aforgenet.com/

Accord
http://accord-framework.net/intro.html

Accord Extensions
https://github.com/dajuric/accord-net-extensions

 GraphicsMagick
https://graphicsmagick.codeplex.com/

ImageMagick.NET  (Magick.NET)
http://www.imagemagick.net/script/api.php#dot-net
http://magick.codeplex.com/

Anyways, maybe good developers generate a discussion about it.

Another issue about image processing: OCR and detect porn images.

I haven't found any good awesome frameworks or libraries.

http://nugetmusthaves.com/Tag/nude
http://stackoverflow.com/questions/713247/what-is-the-best-way-to-programatically-detect-porn-images

OCR
https://code.google.com/p/tesseract-ocr/
https://gist.github.com/yatt/915443

I added this issue for discussion about it. My little experience not enough good to add awesome framework in Image Processing.

**Comment by quozd** [comment]
Hi @kiquenet . We already have [two projects in the list](https://github.com/quozd/awesome-dotnet#image-processing) added by community. You can try them as starting point.

**Comment by kiquenet** [comment]
IMHO, AForge and Accord - Accord Extensions should be added in awesome.NET.
Certainly, I'm newbie about it.

**Comment by Denis-Vlassenko** [comment]
I tend to agree with @kiquenet on both libraries. They are awesome, indeed.
