### ISSUE TITLE
Useful: Which technologies is xxx built on?

### ISSUE THREAD

**Issue by kiquenet** [quozd/awesome-dotnet#59]
Awesome .NET are wondeful .NET libraries and components for use in developments.

Maybe interesting a listing "useful projects" that uses those Awesome.Net.
If they are open source better.

For example, WorkFu App  use "awesome NET" like Autofac, Lucene, Dapper, SignalR, JQuery, Memcached, Booksleeve, Elmah, ...

http://blog.appharbor.com/2012/1/04/featured-app-workfu
Which technologies is WorkFu built on?

WorkFu is built on MVC 3 and utilises: 

Redis, Redis is an open source, BSD licensed, advanced key-value store. It is often referred to as a data structure server since keys can contain strings, hashes, lists, sets and sorted sets.
Memcached, Free & open source, high-performance, distributed memory object caching system
Autofac,  IOC
Lucene,  full-featured text search engine 
Dapper.net, simple object mapper
SignalR, simple real-time web
jQuery, 
Booksleeve,  By offering pipelined, asynchronous, multiplexed and thread-safe access to redis
Elmah,  application-wide error logging facility that is completely pluggable.
MS SQL Server 2008,
 S3 for file storage 
and Postmarkfor mail delivery

We have background services running on separate Amazon instances along with our Redis and Memcached implementations.

**Comment by quozd** [comment]
I think such a list will quickly become place for advertisements. It can't be populated by maintainers.
