### ISSUE TITLE
No clear ordering rules of items within each catetory

### ISSUE THREAD

**Issue by wachulski** [quozd/awesome-dotnet#599]
Is there an order within each category?
If no, then I suggest that some be added. + a word about it in Readme

**Comment by wachulski** [comment]
A quick glimpse over https://github.com/vinta/awesome-python shows me that they make use of lexical  ordering there. Just a little enhancement.

**Comment by pleb** [comment]
Interesting. I think at the moment it is more of a - append to the end of the sub-list

**Comment by pleb** [comment]
Lexical order seems the best

- [ ] We need to update the existing list
- [ ]  We need to update the Readme
- [ ] We need to add a label for incorrect lexical ordering
- [ ] Stretch, update the build to fail when lexical ordering is incorrect

-
