### ISSUE TITLE
mutation testing frameworks/tools

### ISSUE THREAD

**Issue by skorzinetzki** [quozd/awesome-dotnet#635]
I like your list and I got here because I have been looking for a mutation testing framework / tools. unfortunately there is nothing listed right now. I think there is nothing to find right now. but maybe, at any time, we have something that should get listed up here.

**Comment by zihotki** [comment]
What do you mean by that?

**Comment by skorzinetzki** [comment]
What do I mean by mutation testing? Mutation testing can be described as a method, with which you mutate the production code (e.g. "if (a>b)" will become "if (a<b)") and then run your automated test suite. With each mutation at least one test should fail, so that this mutation is killed. Otherwise you may have a lack in your code coverage (or other reasons).
so this is a method to measure the quality of your test suite and goes beyond code coverage metrics.

One concrete tool might be Visual Mutator (https://visualmutator.github.io/web/). But this is not working with current Visual Studio versions. 
Working tools/frameworks for other languages are PIT (http://pitest.org/) for Java or Stryker (http://stryker-mutator.io/) for JavaScript.

**Comment by zihotki** [comment]
Oh, I wasn't aware of such concept, my bad. I tried to see how much it's widespread and it looks to me that adoption of it is not widespread as well as there aren't many libraries/frameworks in .Net supporting it. So I'd rather avoid creating a new specific category and I'd suggest to put it to the Testing category where we have frameworks and libraries related to unit/integration/younameit testing.

**Comment by skorzinetzki** [comment]
Yes, this is the best fit. I did not want to suggest a separate category, but, at any time when available, to list such a framework in the testing category. ;)
On Twitter I got into a conversation with one of the maintainers of Stryker, which I mentioned earlier in this issue. They are planning to start to develop a tool for c#. Sounds promising!

**Comment by pleb** [comment]
@skorzinetzki interesting... PR with new category seems like the right next step

**Comment by philippw** [comment]
The Stryker mutation testing framework has gained inital support for C#. See https://github.com/stryker-mutator/stryker-net.

**Comment by skorzinetzki** [comment]
@philippw yes, I had a first try and it worked in my very simple example. I think it can be listed right now. Or do you wait until it has left it's preview status?

**Comment by skorzinetzki** [comment]
Okay, I can create a pr today. :)

**Comment by zihotki** [comment]
I'm closing the issue since all questions have been covered and PR has been merged. For now let's keep mutation testing under the Testing section, later on we can move it to separate if there will be a plenty of similar projects. Please reopen the issue if needed.
