### ISSUE TITLE
Need Obfuscation Program for .Net

### ISSUE THREAD

**Issue by 3dsoft** [quozd/awesome-dotnet#657]
I need obfuscation program for .Net
like below...

Obfuscar : https://github.com/lextm/obfuscar
ConfuserEx : https://github.com/yck1509/ConfuserEx

**Comment by Jogai** [comment]
- https://github.com/CubeCoders/ConfuserEx-Reborn

**Comment by zihotki** [comment]
This is not the place to ask questions to find some components. This is a listing of awesome (opinionated) components
