### ISSUE TITLE
FluffySpoon.Automation is worth mentioning

### ISSUE THREAD

**Issue by ffMathy** [quozd/awesome-dotnet#687]
It's a library I made which is inspired by the now-dead "FluentAutomation" library.

It is fully async, runs .NET Standard, and has a really cool syntax.

https://github.com/ffMathy/FluffySpoon.Automation

**Comment by zihotki** [comment]
It looks interesting but probalby it won't make it since there are no unit tests (for test automation library, oh my), no automated build, package, and it's too new. But feel free to send a Pull Request according to our contribution guidelines and let's discuss it.

**Comment by ffMathy** [comment]
There is an automated build for it, but I do agree there is no test coverage.
