### ISSUE TITLE
Please add DotSpatial to the GIS section

### ISSUE THREAD

**Issue by sindizzy** [quozd/awesome-dotnet#698]
Please add DotSpatial to the GIS section
https://github.com/DotSpatial/DotSpatial

**Comment by sindizzy** [comment]
Just to add a link??? I'll pass.

**Comment by zihotki** [comment]
All changes to the list are going via PR and review pipeline which makes this list a curated list, there are pros and cons of this approach but overhead is very minor. And it'd have taken you approximately the same amount of time (1-2 mins) to submit a PR via web interface of GitHub as creating this issue.

**Comment by sindizzy** [comment]
Thanks for the info.
