### ISSUE TITLE
Machine Learning: numl

### ISSUE THREAD

**Issue by kiquenet** [quozd/awesome-dotnet#72]
what's about numl ?

Nuget package by sethjuarez

http://blog.adnanmasood.com/2013/10/25/demystification-of-demystifying-machine-learning-using-numl-w-seth-juarez/

http://stephenhaunts.com/2014/08/15/machine-learning-with-numl/

http://stackoverflow.com/questions/3976481/is-there-some-net-machine-learning-library-that-could-for-example-suggest-tag

Reference: @preguntoncabron

**Comment by quozd** [comment]
Looks good for me. 
@kiquenet Feel free to open new PR and add link to Numl

**Comment by quozd** [comment]
@kiquenet do you mind to open a PR with proposed changes? :)

**Comment by kiquenet** [comment]
I'm newbie, I have to learn how-to create PR.

**Comment by devkhan** [comment]
[numl](https://github.com/quozd/awesome-dotnet/commit/05a5025014bfe8d39d82fda6b0567d1a238ed387) added. Closing issue.
