### ISSUE TITLE
Can you add Easy Pdf

### ISSUE THREAD

**Issue by aleGuardiola** [quozd/awesome-dotnet#738]
I am working in this library and I think is awesome :). Can you take a look https://github.com/aleGuardiola/EasyPdf

**Comment by Jogai** [comment]
The purpose of an awesome list on github is to supply a PR with your suggestion, see https://github.com/quozd/awesome-dotnet/blob/master/CONTRIBUTING.md

**Comment by devSoheilAlizadeh** [comment]
PDF version has added with #758

**Comment by Jogai** [comment]
That is something different entirely
