### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [quozd/awesome-dotnet#74]
We are creating a github org for all awesome open source repos. I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction we need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org. What are your thoughts? Let me know if there is anything you'd like to discuss!

**Comment by VPashkov** [comment]
Hi!
Isn't it will same as https://github.com/bayandin/awesome-awesomeness?

**Comment by jeffreyjackson** [comment]
sort of, we are working on creating an open organization to further improve the awesomeness :grimacing: 

1.  By having everything under 1 organization visibility will be increased for all awesome repos -> more stars -> round we go.
2.  Ownership is shared so there is less risk of the repo falling off unsupported.

you'll be made an admin so you'll have the same level of control as you had before.

**Comment by quozd** [comment]
Hi @jeffreyjackson 
Your idea looks promising, but I wont agree to transfer awesome-dotnet repo until most of awesome-awesomeness list will be there. Sorry.

Thank you :)
