### ISSUE TITLE
Where to put Shell Extensions / Windows Enhancements

### ISSUE THREAD

**Issue by Countryen** [quozd/awesome-dotnet#815]
Which category is a library that supports developing shell extensions (like registry, COM-Server, Context Menu) or Windows Enhancements?

There is no "COM (Component Object Model)" neither a "Registry" nor a "Shell Extension" or "Windows Explorer / Browser" category, yet.

I'd like to add [SharpShell](https://github.com/dwmkerr/sharpshell) for managed Shell Extensions
"SharpShell makes it easy to create Windows Shell Extensions using the .NET Framework."

**Comment by pleb** [comment]
PR and create a new category if you like
