### ISSUE TITLE
#passing data

### ISSUE THREAD

**Issue by Sreejapalanivel** [quozd/awesome-dotnet#816]
•	Create two different applications let’s say Application1(.exe) and Application2(.exe)
•	Application1 should have two textbox textBox1 and textBox2.
•	Application2 also have textBox1 and textBox2.
•	User need to give the input (data) in textboxes.
•	When the data enter by user in textBox1 of application1 should simultaneously show in textBox2 of application2 without pressing any button.
•	Passing data between applications is done by the system.
•	The View of data from one application to another application should be the output.
•	Same as when data enter by user in textBox1 of application2 should simultaneously show in textBox2 of application1.
•	The conditions applied are the system should not use any database or files to store data.

**Comment by jwjosefy** [comment]
Don't know exactly what you are trying to achieve here, but one way to do it is using SignalR and connecting the 2 apps. Look here -> https://dotnet.microsoft.com/apps/aspnet/real-time

Despite it says ASP.NET you can use in any platform where dotnet runs, actually.

**Comment by pleb** [comment]
I'm closing this as it's not related to repo
