### ISSUE TITLE
Add https://github.com/michael-wolfenden/Polly

### ISSUE THREAD

**Issue by ghuntley** [quozd/awesome-dotnet#85]
Which section should we slot https://github.com/michael-wolfenden/Polly under?

    Polly is a .NET 3.5 / 4.0 / 4.5 / PCL library that allows developers to express
    transient exception handling policies such as Retry, Retry Forever, Wait and
    Retry or Circuit Breaker in a fluent manner.

**Comment by quozd** [comment]
I think [Misc](https://github.com/quozd/awesome-dotnet#misc) is the best place for now. 
/cc @vladen

**Comment by vladen** [comment]
Definitely, #https://github.com/quozd/awesome-dotnet#misc
