### ISSUE TITLE
Add obfuscation section and corresponding libraries

### ISSUE THREAD

**Issue by KvanTTT** [quozd/awesome-dotnet#850]
For instance, different [ConfuerEx](https://github.com/yck1509/ConfuserEx) forks ([ConfuserEx 2](https://github.com/mkaring/ConfuserEx), [neo-ConfuserEx](https://github.com/XenocodeRCE/neo-ConfuserEx)), [obfuscar](https://github.com/obfuscar/obfuscar) and other.

**Comment by Jogai** [comment]
Send a PR, adding it. Altough I guess it only one version of convuser(ex) can be truly awesome

**Comment by KvanTTT** [comment]
I don't think so. The original version is archived and has a lot of bugs. Meanwhile, the fork by @mkaring works much better and is being under active development.
