### ISSUE TITLE
log4net is not anymore mantained.

### ISSUE THREAD

**Issue by OrbintSoft** [quozd/awesome-dotnet#908]
As of April 1, 2020 Log4Net is a dormant project of Apache Logging Services. The dormant status means the project has been classified as inactive since it has had no recent development activity and there are no active volunteers to perform code reviews, commit code, or perform releases. Although it is possible volunteers might choose to participate in the future, it is best to assume there will be not future development or releases.

https://logging.apache.org/log4net/

I think we should remove the library from the list.

**Comment by sp9usb** [comment]
👍

**Comment by gep13** [comment]
@OrbintSoft do you have a link to where it is marked as dormant?  The link that you provide in the issue doesn't mention anything about that.  Thanks

**Comment by OrbintSoft** [comment]
It seems that they found a new maintainer, so the project is active again, even if not very active.

https://web.archive.org/web/20200426193744/https://logging.apache.org/log4net/

I close the issue, because now the project is active, but considering the low support and slow development, we should consider if keep it on dotnet awesome.

**Comment by Jogai** [comment]
I'd vote for removal. Used it a long time ago, but switched to nlog. Its more efficient, easier to work with and designed for .net (log4net is a port of log4j). It also has structured logging which seems more popular these days.
