### ISSUE TITLE
C# to JavaScript compiler, now on .NET50 (Addition to list)

### ISSUE THREAD

**Issue by CastleSoft** [quozd/awesome-dotnet#970]
https://github.com/theolivenbaum/h5

C# to JavaScript compiler, now on .NET50

H5 is a modern fork of the original Bridge C# to Javascript compiler, updated to support multi-platform development using .NET 5.0 and .NET Standard 2.0 projects while dropping support for legacy features and dependencies.

**Comment by Jogai** [comment]
It does look awesome, you should make a PR
