### ISSUE TITLE
Tesserae is a UI toolkit for building websites entirely in C#, inspired by Microsoft's Fluent UI toolkit. (Add to list)

### ISSUE THREAD

**Issue by CastleSoft** [quozd/awesome-dotnet#971]
https://github.com/curiosity-ai/tesserae

Tesserae is a UI toolkit for building websites entirely in C#, inspired by Microsoft's Fluent UI toolkit.

It uses the h5 C# to Javascript compiler to provide an easy to use, strongly typed UI development experience.

**Comment by Jogai** [comment]
see https://github.com/quozd/awesome-dotnet/blob/master/CONTRIBUTING.md
